### PR TITLE
Changing web dir to en dir and its references #4

### PR DESCRIPTION
**Pull request by GankousKhan**

### CODE REVIEW

**Review by instafluff — CHANGES_REQUESTED** [review]
Thank you for this PR! It looks like it deleted some of the files in the root folder like the README and license along with the new `de` folder. Would it be all right to ask if you could keep those other files in the PR?

**Comment by GankousKhan** [comment]
> 
> 
> Thank you for this PR! It looks like it deleted some of the files in the root folder like the README and license along with the new `de` folder. Would it be all right to ask if you could keep those other files in the PR?

Sure thing. I couldnt figure out why it kept marking those as deleted despite not touching them. Will revert out after work.

**Comment by GankousKhan** [comment]
Alright I believe this is all of them. No idea why those were marked as deleted. I actually had them on my local (and even stranger yet in my staging it showed them as being deleted, but also added for some reason). Forgot to attach issue webhook to the commit. https://github.com/christopher-lamb/ComfyDictionary/commit/521b4f818853aaca0336aa6d972ffcec65fb4491

**Comment by instafluff** [comment]
Thank you so much!!

**Pull request merged**
